name: nfcreadertools
description: "NFC Reader and Writer developed in Flutter."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.8

  # responsive size
  flutter_screenutil: ^5.9.3

  # state management
  provider: ^6.1.5

  # router
  go_router: ^15.1.2

  # svg
  flutter_svg: ^2.1.0

  # lottie animation
  lottie: ^3.3.1

  # nfc management
  nfc_manager: ^3.5.0

  # local storage 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # cached network image
  cached_network_image: ^3.4.1

  # url launcher
  url_launcher: ^6.3.1

  # toast
  toastification: ^3.0.2

  # contacts
  flutter_contacts: ^1.1.9+2

  # firebase
  firebase_core: ^3.13.1

  # firebase auth
  firebase_auth: ^5.5.4

  # google sign in
  google_sign_in: ^6.3.0

  # apple sign in
  sign_in_with_apple: ^7.0.1

  # cloud firestore
  cloud_firestore: ^5.6.8

  # share plus
  share_plus: ^11.0.0

  # youtube player 
  youtube_player_flutter: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  # app package name for both android and ios
  change_app_package_name: ^1.4.0


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/svg/
    - assets/lottie/
    - assets/img/svg/
    - assets/img/jpg/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DM_Sans/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DM_Sans/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DM_Sans/DMSans-SemiBold.ttf
          weight: 600


