// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgekAXWRJntW_5n3MkJn84QBBcnQ_0-rI',
    appId: '1:901150215905:web:fcbf946161fcbd8aa4b1a0',
    messagingSenderId: '901150215905',
    projectId: 'nfcreaderwriterapp',
    authDomain: 'nfcreaderwriterapp.firebaseapp.com',
    storageBucket: 'nfcreaderwriterapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5mNMkD5Jemg-ZJxAk7_qsaUGqqOMNe1w',
    appId: '1:901150215905:android:90c9dfd9f5faa7b5a4b1a0',
    messagingSenderId: '901150215905',
    projectId: 'nfcreaderwriterapp',
    storageBucket: 'nfcreaderwriterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfWkBRwNxsqoPeIKbVEtGEI5PzIJkXJjY',
    appId: '1:901150215905:ios:10bee5835e733d0da4b1a0',
    messagingSenderId: '901150215905',
    projectId: 'nfcreaderwriterapp',
    storageBucket: 'nfcreaderwriterapp.firebasestorage.app',
    androidClientId: '901150215905-7sig5mch56hj7ku76ga497akrus0s1ei.apps.googleusercontent.com',
    iosClientId: '901150215905-86gg0ha9f4vh3a8l5fu76f8g17cdngnh.apps.googleusercontent.com',
    iosBundleId: 'com.princeappstudio.nfctools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfWkBRwNxsqoPeIKbVEtGEI5PzIJkXJjY',
    appId: '1:901150215905:ios:a41138f520879583a4b1a0',
    messagingSenderId: '901150215905',
    projectId: 'nfcreaderwriterapp',
    storageBucket: 'nfcreaderwriterapp.firebasestorage.app',
    iosBundleId: 'com.example.nfcreadertools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgekAXWRJntW_5n3MkJn84QBBcnQ_0-rI',
    appId: '1:901150215905:web:8d5b6b2299c1898ba4b1a0',
    messagingSenderId: '901150215905',
    projectId: 'nfcreaderwriterapp',
    authDomain: 'nfcreaderwriterapp.firebaseapp.com',
    storageBucket: 'nfcreaderwriterapp.firebasestorage.app',
  );
}